window.LEAGUE_premier = [
  { name: "Liverpool", short: "LIV", image: "images/liverpool.png" },
  { name: "Manchester City", short: "MCI", image: "images/man_city.png" },
  { name: "Arsenal", short: "ARS", image: "images/arsenal.png" },
  { name: "Chelsea", short: "CHE", image: "images/chelsea.png" },
  { name: "Tottenham Hotspur", short: "TOT", image: "images/tottenham.png" },
  { name: "Everton", short: "EVE", image: "images/everton.png" },
  { name: "Manchester United", short: "MUN", image: "images/man_united.png" },
  { name: "Newcastle United", short: "NEW", image: "images/newcastle.png" },
  { name: "Aston Villa", short: "AVL", image: "images/aston_villa.png" },
  { name: "Brighton & Hove Albion", short: "BHA", image: "images/brighton.png" },
  { name: "West Ham United", short: "WHU", image: "images/west_ham.png" },
  { name: "Bournemouth", short: "BOU", image: "images/bournemouth.png" },
  { name: "Crystal Palace", short: "CRY", image: "images/crystal_palace.png" },
  { name: "Brentford", short: "BRE", image: "images/brentford.png" },
  { name: "Fulham", short: "FUL", image: "images/fulham.png" },
  { name: "Leeds United", short: "LEE", image: "images/leeds.png" },
  { name: "Burnley", short: "BUR", image: "images/burnley.png" },
  { name: "Sunderland", short: "SUN", image: "images/sunderland.png" },
  { name: "Wolves", short: "WOL", image: "images/wolves.png" },
  { name: "Nottingham Forest", short: "NFO", image: "images/forest.png" }
];
